name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm test

      - name: Save Cypress Test Results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: cypress/reports

  generate-reports:
    needs: cypress-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Cypress Test Results
        uses: actions/download-artifact@v2
        with:
          name: cypress-test-results

      - name: Configure Git
        run: |
          git config --global user.email "rahulkundu2016@gmail.com"
          git config --global user.name "rahul8436"

      - name: Push Reports to gh-pages Branch
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          git pull origin gh-pages --ff-only  # Perform a fast-forward merge
          mkdir -p ${{ github.run_number }}
          mv cypress/reports/* ${{ github.run_number }}
          git add .
          git commit -m "Add reports for run ${{ github.run_number }}"
          git push origin gh-pages
