name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests'
        required: true
        default: 'autopush'
        type: choice
        options:
          - autopush
          - staging
          - production

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm test
        continue-on-error: true

      - name: Save Cypress Test Results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: cypress/reports

  generate-reports:
    needs: cypress-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Cypress Test Results
        uses: actions/download-artifact@v2
        with:
          name: cypress-test-results

      - name: Configure Git
        run: |
          git config --global user.email "rahulkundu2016@gmail.com"
          git config --global user.name "rahul8436"

      - name: Push Reports to gh-pages Branch
        run: |
          # Determine the environment folder based on input
          if [[ "${{ github.event_name }}" == "push" ]]; then
            ENVIRONMENT="autopush"
          else
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          fi

          BASE_DIR="${ENVIRONMENT}/${{ github.run_number }}"

          git fetch origin gh-pages:gh-pages
          git checkout gh-pages || git checkout -b gh-pages
          
          # Create the environment directory if it doesn't exist
          mkdir -p ${ENVIRONMENT}

          # Create the run number directory
          mkdir -p ${BASE_DIR}
          
          # Move the HTML report to the environment folder
          mv html ${BASE_DIR}

          # Add and commit the changes
          git add .
          git commit -m "Add reports for ${ENVIRONMENT} run ${{ github.run_number }}"
          git push origin gh-pages
